server.port: 8080
spring.rabbitmq.host: rabbit
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

spring:
  cloud:
    stream:
      poller:
        fixed-delay: 60000000
      function:
        definition: messageSupplier;
      bindings:
        messageSupplier-out-0:
          destination: messages