openapi: 3.0.0
info:
  title: Writer API
  description: API for message writer, responsible for sending messages into rabbit in the background and able to send specific message when used the /messages endpoint.
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /messages/{message}:
    post:
      summary: Returns the sent message.
      parameters:
        - in: path
          name: message
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A String showing the sent message
          content:
            application/json:
              schema:
                type: string